spring.devtools.livereload.enabled: false

---
spring:
    profiles: production
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/two

# TODO: add the credentials to your production redis
# preferably using environment variables

# spring.profiles.active: redis
#    redis:
#      password:
#      host:
#      port:
